# Generated by Django 5.0 on 2023-12-28 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("category_persian", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Faculties",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("faculty", models.CharField(max_length=50)),
                ("faculty_persian", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Languages",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("language", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Publishers",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("publisher", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("signatory", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=30)),
                ("pages", models.IntegerField()),
                ("edition", models.IntegerField()),
                ("publication_year", models.DateField()),
                ("description", models.TextField()),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_managment.authors",
                    ),
                ),
                (
                    "faculty_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_managment.faculties",
                    ),
                ),
                (
                    "language_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_managment.languages",
                    ),
                ),
                (
                    "publisher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_managment.publishers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Copies",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=20)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_managment.books",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="eBooks",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("extension", models.CharField(max_length=30)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_managment.books",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("news_title", models.CharField(max_length=255)),
                ("news_summary", models.TextField()),
                ("news_details", models.TextField()),
                ("news_ref", models.CharField(max_length=255)),
                ("news_title_persian", models.CharField(max_length=255)),
                ("news_details_persian", models.TextField()),
                ("news_ref_persian", models.CharField(max_length=255)),
                ("news_date", models.DateField()),
                ("fileext", models.CharField(max_length=3)),
                (
                    "faculties_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_managment.faculties",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sections",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("section", models.CharField(max_length=100)),
                ("section_persian", models.CharField(max_length=100)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_managment.categories",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="books",
            name="section_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="book_managment.sections",
            ),
        ),
    ]
